// Clinic Solutions — FUJIFILM Business Innovation + Crestron
// All figures in HKD. Mid-range HK market pricing. prereqs = site infrastructure required.

export const CATALOG = {
  currency: "HKD",
  items: {
    mfd:         { name: "Fujifilm Apeos C2560 MFD",               brand: "Fujifilm",  note: "A3 colour MFD, scan-to-EMR, secure release",                       material: 26000, install: 2200, unit: "ea",
                   prereqs: ["Gigabit Ethernet port", "220V power outlet", "EMR system with scan-to-folder or scan-to-email configured"] },
    labelPrinter:{ name: "Zebra ZD421 Thermal Label Printer",      brand: "Zebra",     note: "Patient / specimen labelling",                                     material:  2000, install:  350, unit: "ea",
                   prereqs: ["USB or Ethernet connection to clinic PC", "220V power outlet", "Label roll stock (consumable, not included)"] },
    barcodeScanner:{ name: "Honeywell Xenon 2D Barcode Scanner",   brand: "Honeywell", note: "Check-in & document capture",                                      material:  1100, install:  180, unit: "ea",
                   prereqs: ["USB port on host PC"] },
    pcTerminal:  { name: "Dell OptiPlex 3000 PC Terminal",         brand: "Dell",      note: "Reception / front-desk workstation",                               material:  5800, install:  500, unit: "ea",
                   prereqs: ["Gigabit Ethernet port", "220V power outlet", "Windows domain or workgroup configured", "EMR client software licence (not included)"] },
    eizoMonitor: { name: "Eizo FlexScan EV2495 Monitor",           brand: "Eizo",      note: "24.1\" clinical display, USB-C, calibrated",                       material:  4800, install:  600, unit: "ea",
                   prereqs: ["HDMI or DisplayPort source device (PC or HDMI extender)", "220V power outlet"] },
    dellPC:      { name: "Dell Precision 3660 Clinical PC",        brand: "Dell",      note: "Consultation workstation w/ EMR",                                  material:  9500, install:  500, unit: "ea",
                   prereqs: ["Gigabit Ethernet port", "220V power outlet", "Windows domain or workgroup configured", "EMR client software licence (not included)"] },
    ipCamera:    { name: "Hikvision 4MP PoE Dome Camera",          brand: "Hikvision", note: "DS-2CD2143G2-I, ceiling / wall mount",                             material:   900, install:  600, unit: "ea",
                   prereqs: ["PoE switch port (IEEE 802.3af, 15.4W min)", "NVR or VMS software for recording and playback", "Ceiling or wall mounting surface"] },
    nursePC:     { name: "Dell OptiPlex 3000 Nurse PC",            brand: "Dell",      note: "Treatment-room workstation",                                       material:  5800, install:  500, unit: "ea",
                   prereqs: ["Gigabit Ethernet port", "220V power outlet", "Windows domain or workgroup configured", "EMR client software licence (not included)"] },
    medScanner:  { name: "Zebra DS2208 Medication Scanner",        brand: "Zebra",     note: "Barcode med dispensing check",                                     material:  1800, install:  250, unit: "ea",
                   prereqs: ["USB port on nurse station PC", "Medication barcode database in EMR or dispensing system"] },
    server:      { name: "Dell PowerEdge T360 Server",             brand: "Dell",      note: "On-prem EMR / application server",                                 material: 52000, install: 4500, unit: "ea",
                   prereqs: ["Dedicated 220V / 16A power circuit", "UPS protection (included in Backup package)", "Gigabit Ethernet uplink to core switch", "Static IP address", "Rack or tower space in dedicated server room", "Server OS licence — Windows Server or Linux (not included)", "EMR application licence (not included)"] },
    nas:         { name: "Synology DS1823xs+ NAS (40TB)",          brand: "Synology",  note: "Encrypted local backup, 40TB usable",                              material: 18500, install: 1800, unit: "ea",
                   prereqs: ["220V power outlet", "Gigabit Ethernet port to core switch", "UPS protection", "Backup policy configured (DSM software included)"] },
    utm:         { name: "Fortinet FortiGate 60F UTM",             brand: "Fortinet",  note: "Managed gateway, IPS + content filter, 1-yr bundle",               material:  9500, install: 2000, unit: "ea",
                   prereqs: ["Active ISP WAN circuit with static or dynamic IP", "Ethernet handoff from ISP modem or ONT", "220V power outlet", "FortiCare support licence (included in 1-yr bundle — renewal required annually)"] },
    ups:         { name: "APC Smart-UPS SMT3000IC (3kVA)",         brand: "APC",       note: "Online UPS w/ network monitoring card",                            material:  8000, install:  700, unit: "ea",
                   prereqs: ["Dedicated 220V / 16A power circuit", "Rack space (2U) or floor space near server equipment", "Network port for SmartConnect monitoring card"] },
    wifiAP:      { name: "TP-Link EAP670 Wi-Fi 6 AP",             brand: "TP-Link",   note: "Ceiling AP, PoE+, controller-managed",                             material:  1800, install:  700, unit: "ea",
                   prereqs: ["PoE+ switch port (IEEE 802.3at, 25.5W)", "Gigabit Ethernet backbone cabling to ceiling", "Omada Software Controller or Omada Cloud for centralised management (free)"] },
    avSystem:    { name: "Logitech Rally Bar Mini AV System",      brand: "Logitech",  note: "Video bar, AI framing, Teams / Zoom / Meet certified",             material: 20000, install: 2500, unit: "set",
                   prereqs: ["HDMI display 55\" or larger recommended", "220V power outlet", "Gigabit Ethernet for network features", "Microsoft Teams / Zoom / Google Meet room licence (not included)"] },
    rack:        { name: "27U Server Rack & Cable Management",     brand: "Fujifilm",  note: "27U rack, PDU, cable dressing",                                    material:  6500, install: 2000, unit: "ea",
                   prereqs: ["Dedicated server room with min. 0.6m × 1.0m floor space", "220V multi-socket PDU (included)", "Adequate ventilation or air-conditioning — server room ambient temp below 27°C"] },
    switch:      { name: "TP-Link TL-SG3452XP PoE+ Switch",       brand: "TP-Link",   note: "48-port L2+ managed, 500W PoE budget",                             material:  8000, install: 1200, unit: "ea",
                   prereqs: ["1U rack space in server rack", "Uplink connection to UTM / core router", "220V power via rack PDU", "Omada Controller for management (optional, free)"] },
    cabling:     { name: "Structured Cabling Drop (Cat6A)",        brand: "Fujifilm",  note: "Per outlet: cable, faceplate, patch panel termination, certified test", material: 750, install: 900, unit: "drop",
                   prereqs: ["Conduit or cable trunking pathway from server room to each outlet", "Patch panel in server rack", "Approved floor plan with outlet locations provided before installation"] },
    // ---- Crestron AV Products -----------------------------------------------
    hdTx101:     { name: "Crestron HD-TX-101-C-E",                 brand: "Crestron",  note: "DM Lite HDMI over CATx transmitter — DISCONTINUED, limited stock",  material:   600, install:  400, unit: "ea",
                   prereqs: ["⚠ DISCONTINUED — specify HD-TXC-4KZ-101 for new installations", "Compatible DM Lite receiver (HD-RX-101-C-E) required at display end — also discontinued", "CAT5e or higher UTP, max 70m for HD / 40m for 4K", "24VDC 1.25A power adapter (included in box)"] },
    hdTxc4kz:    { name: "Crestron HD-TXC-4KZ-101 4K Transmitter", brand: "Crestron", note: "4K60 4:4:4 HDR HDMI over CATx, 40m@4K / 70m@HD, bidirectional RS-232 & IR", material: 5000, install: 800, unit: "ea",
                   prereqs: ["Matching DM Essentials receiver (HD-RXC-4KZ-101) required at display end — priced separately", "CAT5e or higher UTP cable, max 40m for 4K60 / 70m for 1080p", "Power: PoE from compatible DM Essentials switcher, or included 24VDC adapter", "HDMI source device and HDMI display at the destination end"] },
    airMedia:    { name: "Crestron AirMedia AM-3200",               brand: "Crestron",  note: "Wireless & wired presentation receiver, PoE+, 4K HDMI out, AES-128 encrypted", material: 14000, install: 1200, unit: "ea",
                   prereqs: ["PoE+ switch port (IEEE 802.3at, 25.5W minimum) — or optional 24VDC 1.25A power adapter", "HDMI display connected to AM-3200 HDMI output port", "Gigabit Ethernet connection to clinic LAN", "Presenting devices need Crestron AirMedia Connect app — Windows / macOS / iOS / Android (free download)", "Guest isolation: separate guest SSID or VLAN recommended for visitor presenters"] },
    dmNvx:       { name: "Crestron DM-NVX-350 AV-over-IP",         brand: "Crestron",  note: "4K60 AV-over-IP encoder/decoder, Gigabit, PoE++, per unit price",   material: 20000, install: 1800, unit: "ea",
                   prereqs: ["PoE++ / UPOE switch port (60W per unit) — standard PoE (15W) or PoE+ (25W) are insufficient", "Gigabit Ethernet network; minimum 350 Mbps dedicated bandwidth per active 4K stream", "Dedicated AV VLAN strongly recommended to isolate high-bandwidth video from clinical data traffic", "HDMI source at encoder end; HDMI display at decoder end for each video path", "Sold and deployed in encoder + decoder pairs — minimum 2 units per video route", "DM NVX Director management software (free, requires Windows Server — already included if Dell PowerEdge server is provisioned)"] },
  },

  rooms: [
    {
      id: "reception", name: "Reception / Waiting Area", zone: "Front of House",
      blurb: "Patient check-in, document capture and front-desk workstations.",
      count: 1, fixedCount: true,
      lines: [
        { item: "mfd",            qty: 1 },
        { item: "labelPrinter",   qty: 2 },
        { item: "barcodeScanner", qty: 2 },
        { item: "pcTerminal",     qty: 2 },
      ],
    },
    {
      id: "consult", name: "Consultation Room", zone: "Clinical",
      blurb: "Diagnostic display, clinical PC, patient-facing screen extension and in-room security.",
      count: 2,
      lines: [
        { item: "eizoMonitor", qty: 1 },
        { item: "dellPC",      qty: 1 },
        { item: "ipCamera",    qty: 1 },
        { item: "hdTxc4kz",   qty: 1 },
      ],
    },
    {
      id: "treatment", name: "Treatment Room", zone: "Clinical",
      blurb: "Nurse workstation and monitoring for procedures and minor treatment.",
      count: 1,
      lines: [
        { item: "nursePC",  qty: 1 },
        { item: "ipCamera", qty: 1 },
      ],
    },
    {
      id: "nurse", name: "Nurse Station", zone: "Clinical",
      blurb: "Shared dispensing, labelling and medication verification hub.",
      count: 1,
      lines: [
        { item: "pcTerminal",   qty: 2 },
        { item: "labelPrinter", qty: 1 },
        { item: "medScanner",   qty: 1 },
      ],
    },
    {
      id: "backup", name: "Backup / Storage Room", zone: "Infrastructure",
      blurb: "On-prem server, encrypted backup, managed gateway and power protection.",
      count: 1,
      lines: [
        { item: "server", qty: 1 },
        { item: "nas",    qty: 1 },
        { item: "utm",    qty: 1 },
        { item: "ups",    qty: 1 },
        { item: "rack",   qty: 1 },
        { item: "switch", qty: 1 },
      ],
    },
    {
      id: "network", name: "Network & Connectivity", zone: "Infrastructure",
      blurb: "Site-wide cabling, ceiling cameras and Wi-Fi coverage.",
      count: 1, fixedCount: true,
      lines: [
        { item: "ipCamera", qty: 4 },
        { item: "wifiAP",   qty: 2 },
        { item: "cabling",  qty: 24 },
      ],
    },
    {
      id: "conference", name: "Conference / AV Corner", zone: "Front of House",
      blurb: "Video collaboration, wireless presentation and room scheduling for case reviews.",
      count: 1,
      lines: [
        { item: "avSystem", qty: 1 },
        { item: "airMedia", qty: 1 },
      ],
    },
    {
      id: "telemedicine", name: "Telemedicine Hub", zone: "Clinical",
      blurb: "Crestron AV-over-IP for remote consultation, surgical video streaming and multi-room imaging distribution.",
      count: 0,
      lines: [
        { item: "dmNvx",   qty: 2 },
        { item: "hdTxc4kz", qty: 2 },
      ],
    },
  ],

  rates: {
    contingency:       0.05,
    projectManagement: 0.08,
    warranty:          0.06,
  },
};
